#server:
#  port: 8500
#  servlet:
#    context-path: /cloud-bus
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka
spring:
  application:
    name: cloud-bus
  rabbitmq:
    host: 192.168.8.73
    port: 5672
    username: springcloud
    password: 123456
